[package]
name = "ttc-bot"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { path = "../serenity", features = ["client", "gateway", "rustls_backend", "model", "framework", "standard_framework", "collector"] }
clap = "2.33.3"
tokio = { version = "1.14", features = ["macros", "rt-multi-thread"]}
regex = "1.5.4"
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "postgres", "chrono", "macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
chrono = "0.4"
dotenv = "0.15"
rand = "0.8.4"
env_logger = "0.9.0"
log = { version = "0.4.14", features = ["std"] }
libloading = "0.7"
ttc-bot-common = { path = "../ttc-bot-common" }
lazy_static = "1.4"

[profile.release]
lto = "fat"
codegen-units = 1
